# Numpy

-Kurulum: numpy.org-->install da yazar.

    -Windows kullananlar icin:
    
        --baslat-->cmd yaz-->terminali calistir-->asagidakileri yaz.
            conda install numpy
            conda install matplotlib
            conda install pandas
 
-Numpy: Lineer cebir kutuphanesidir.

-Kullanimi: numpy.org-->documentation da yazar.

-Numpy kutuphanesini kullanmak icin: import numpy as np

In [1]:
import numpy as np

## Numpy dizileri (Numpy Arrays):

-Tek boyutlu diziler

-Iki boyutlu diziler (Matrixler)

In [2]:
benimListem=[20,30,40]

In [3]:
type(benimListem)

list

In [6]:
np.array(benimListem) #numpy dizisi(listesi) yapmak icin: np.array

array([20, 30, 40])

In [7]:
type(np.array(benimListem)) #numpy in icinden tureyen bir nesne

numpy.ndarray

In [8]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [9]:
matrixListesi

[[10, 20, 30], [20, 30, 40], [30, 40, 50]]

In [19]:
matrixListesi[1][0]

20

In [11]:
numpyMatrixListesi=np.array(matrixListesi)

In [20]:
numpyMatrixListesi[1][0] #numpy dizisinde index kullanimi

20

In [21]:
numpyMatrixListesi[1,0] #numpy dizisinde index kullanimi

20

# Numpy Metotları:

.arange()

.zeros()

.ones()

.linspace()

.eye()

.random()

    .random.randn()    
    .random.randint()

## arange:

Belirlenen aralikta numpy dizisi olusturur:

    (start, finish, step size)

In [33]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [34]:
np.arange(0,10) #0 dan 10 a kdr numpy dizisi olusturur.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(0,10,2) 

array([0, 2, 4, 6, 8])

## zeros:

0 lardan olusan dizi olusturur.

In [36]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
np.zeros((2,3)) #2x3 luk bir 0 matrisi olusturur

array([[0., 0., 0.],
       [0., 0., 0.]])

## ones

1'lik matris olusturur.

In [38]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

## linspace

belirlenen aralikta, esit aralikli sayilar olusturur:

    (baslangic, bitis, kac tane)

In [40]:
np.linspace(0,20,6) #0 ile 20 arasinda, 20 dahil, esit aralikli 6 tane sayi olustur.

array([ 0.,  4.,  8., 12., 16., 20.])

## eye:

birim matris olusturur. ana köşegeni 1'lerden ve diğer elemanları 0'lardan oluşan n × n boyutlu bir kare matristir.

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random:

Standard normal dagilima uygun rastgele sayilar dondurur:

    -randn: float değer verir.
    -randint: int değer verir.

In [42]:
np.random.randn(8) #randn: deger dizisi dondurur. Rasgele 8 tane-float degerler dondurur

array([ 0.94856199, -1.14392294,  0.81620658, -1.50228128,  0.84836113,
       -1.12615407,  1.13011067,  0.64786603])

In [43]:
np.random.randn(3,3) #float degerlerden olusan bir matrix dondurur

array([[-1.47591803, -0.15919506,  1.7766799 ],
       [ 0.49248867,  0.59655528, -0.4737452 ],
       [-2.24444229, -0.76216089, -0.02578099]])

In [44]:
np.random.randint(1,10) #randint: int bir deger dondurur. 1 ile 10 arasinda int bir deger.

6

In [45]:
np.random.randint(1,10,5) #1 ile 10 arasinda, rastgele 5 tane int deger dondurur.

array([5, 6, 5, 1, 4])

## Numpy Dizi Metotlari:

.reshape()

.max()

.min()

.argmax()

.argmin()

.copy()

In [49]:
numpyDizi1 = np.arange(20) #0 dan 20 ye kdr bir dizi olusturur
numpyDizi1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
numpyDizi2 = np.random.randint(0,100,5) #0 ile 100 arasinda, 5 int deger
numpyDizi2

array([60, 38, 60, 49, 13])

In [52]:
numpyDizi1.reshape(4,5) #Diziyi matrix e cevirir.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
numpyDizi2.max() #Dizideki max deger. numpyDizi2.max() = np.max(numpyDizi2)

60

In [54]:
numpyDizi2.min() #Dizideki min deger. numpyDizi2.min() = np.min(numpyDizi2)

13

In [55]:
numpyDizi2.argmax() #Dizideki max degerin index i

0

In [56]:
numpyDizi2.argmin() #Dizideki min degerin index i

4

In [66]:
numpyDizi2Kopya = numpyDizi2.copy()
numpyDizi2Kopya

array([60, 38, 60, 49, 13])

## Numpy indexler:

In [57]:
diziIndex1 = np.arange(0,15)
diziIndex1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
diziIndex1[2]

2

In [59]:
diziIndex1[3:8] #3 den 8 e kdr, 8 dahil dgl.

array([3, 4, 5, 6, 7])

In [60]:
diziIndex1[3:8] = 70 #3 den 8 e kdr olan degerleri,8 dahil dgl, 70 yap
diziIndex1

array([ 0,  1,  2, 70, 70, 70, 70, 70,  8,  9, 10, 11, 12, 13, 14])

In [61]:
diziIndex2 = np.arange(0,24)
diziIndex2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [62]:
slicingDizi = diziIndex2[4:9]
slicingDizi

array([4, 5, 6, 7, 8])

In [63]:
diziIndex2 #dizinin orijinali duruyor

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [64]:
slicingDizi[:] = -40 #[:] tum elemanlari degistir
slicingDizi

array([-40, -40, -40, -40, -40])

In [65]:
diziIndex2 #bu sefer dizinin orijinali de degisti. Slicing ile aldigimiz sayilar da degisti.
#Numpy dizilerinde, dizi icerisinden bir parca alinip degisiklik yapildiginda, yapilan degisiklikler orijinal diziye de yansir

array([  0,   1,   2,   3, -40, -40, -40, -40, -40,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [67]:
diziIndex2Kopya = diziIndex2.copy() #bu nedenle kopyasini kullanabiliriz

## Matrix indexler:

In [68]:
matrixListesi2 = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
matrixListesi2

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [69]:
matrixDizisi = np.array(matrixListesi2)
matrixDizisi

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [70]:
matrixDizisi[1][2] #matrix index yontem1

60

In [71]:
matrixDizisi[1,2] #matrix index yontem2

60

In [72]:
matrixDizisi[1:,2] #1. satirdan sonrasini getir + 2. indexlerini getir

array([60, 90])

In [73]:
matrixDizisi[2:,1:] #2. satirdan sonrasini getir + 1. indexten sonrasini getir

array([[80, 90]])

In [74]:
matrixDizisi[[0,2]] #0. ve 2. indexleri getir

array([[10, 20, 30],
       [70, 80, 90]])

## Numpy operasyonlar:

In [78]:
diziOperasyon1 = np.random.randint(1,100,20) #1 ile 100 arasinda 20 tane int sayi.
diziOperasyon1

array([38, 61, 56, 81, 70,  6, 31, 24, 92, 29, 30, 16, 92, 14, 90, 76,  9,
       96, 27, 71])

In [79]:
diziOperasyon1 > 24 #24 den buyukleri goster, snc bool gosterilir

array([ True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True, False,  True, False,  True,  True, False,  True,
        True,  True])

In [80]:
sonucBoolean = diziOperasyon1 > 24
sonucBoolean

array([ True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True, False,  True, False,  True,  True, False,  True,
        True,  True])

In [84]:
diziOperasyon1[sonucBoolean] #yalnizca True olanlari filtreler

array([38, 61, 56, 81, 70, 31, 92, 29, 30, 92, 90, 76, 96, 27, 71])

In [85]:
diziOperasyon2 = np.arange(2,24) #2 den 24 e kdr dizi
diziOperasyon2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23])

In [86]:
diziOperasyon2 + diziOperasyon2 #direk toplar

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38, 40, 42, 44, 46])

In [88]:
diziOperasyon2 - diziOperasyon2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [89]:
diziOperasyon2 * diziOperasyon2

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196,
       225, 256, 289, 324, 361, 400, 441, 484, 529])

In [90]:
diziOperasyon2 / diziOperasyon2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.])

In [91]:
diziOperasyon3 = [4,9,16,36,81]

In [92]:
np.sqrt(diziOperasyon3) #tum elemanlarin karekokunu alir

array([2., 3., 4., 6., 9.])

In [93]:
np.max(diziOperasyon3) #max deger. numpyDizi2.max() = np.max(numpyDizi2)

81

In [94]:
np.min(diziOperasyon3) #min deger. numpyDizi2.min() = np.min(numpyDizi2)

4