In [1]:
import numpy as np

In [2]:
benimListem=[20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
type(np.array(benimListem))

numpy.ndarray

In [7]:
matrixListesi=[[10,20,30],[20,30,40],[30,40,50]]

In [8]:
matrixListesi

[[10, 20, 30], [20, 30, 40], [30, 40, 50]]

In [9]:
matrixListesi[1][2]

40

In [12]:
numpyMatrixListesi=np.array(matrixListesi)

In [13]:
numpyMatrixListesi[1,2]

40

## arange

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

## ones

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

## linspace

In [23]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

## eye

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [31]:
np.random.randn(8)

array([-0.04012715, -2.02142148, -1.19556745,  0.48011609,  2.21991001,
        0.08509921,  1.18745067, -0.27275964])

In [28]:
np.random.randn(3,3)

array([[-0.2278163 , -0.15478248,  0.37730332],
       [-0.89141811,  0.43078962,  1.48733792],
       [-0.48997762,  0.95054679, -1.44541325]])

In [30]:
np.random.randint(0,10)

8

In [37]:
np.random.randint(1,10,5)

array([5, 6, 7, 3, 3])

randn: float değer verir.
randint: int değer verir.

In [38]:
numpyDizi1=np.arange(5)
numpyDizi1

array([0, 1, 2, 3, 4])

In [41]:
numpyDizi2=np.random.randint(0,100,5)
numpyDizi2

array([44, 19, 34, 19, 13])

## numpy dizi metodlar

In [48]:
numpyDiziMetod=np.arange(20)
numpyDiziMetod

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
numpyDiziMetod.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [50]:
numpyDiziMetod.max()

19

In [51]:
numpyDiziMetod.min()

0

## numpy indexler

In [56]:
diziIndex1=np.arange(0,15)
diziIndex1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
diziIndex1[2]

2

In [58]:
diziIndex1[3:8]

array([3, 4, 5, 6, 7])

In [61]:
diziIndex1[3:8]=70
diziIndex1

array([ 0,  1,  2, 70, 70, 70, 70, 70,  8,  9, 10, 11, 12, 13, 14])

In [63]:
diziIndex2=np.arange(0,24)
diziIndex2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [67]:
slicingDizi=diziIndex2[4:9]
slicingDizi

array([4, 5, 6, 7, 8])

In [68]:
diziIndex2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [69]:
slicingDizi[:]=-40
slicingDizi

array([-40, -40, -40, -40, -40])

In [70]:
diziIndex2

array([  0,   1,   2,   3, -40, -40, -40, -40, -40,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [73]:
diziIndex2Kopya=diziIndex2.copy()

## matrix indexler

In [84]:
matrixListesi2=[[10, 20, 30], [40, 50, 60], [70, 80, 90]]
matrixListesi2

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [85]:
matrixDizisi=np.array(matrixListesi2)
matrixDizisi

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [86]:
matrixDizisi[1][2]

60

In [87]:
matrixDizisi[1,2]

60

In [88]:
matrixDizisi[1:,2]

array([60, 90])

In [90]:
matrixDizisi[2:,1:]

array([[80, 90]])

In [91]:
matrixDizisi[[0,2]]

array([[10, 20, 30],
       [70, 80, 90]])

## numpy operasyonlar

In [100]:
diziOperasyon1=np.random.randint(1,100,20)
diziOperasyon1

array([23, 73, 19, 20, 67, 27, 21,  2, 11, 38, 29, 72, 16, 21, 14, 32, 41,
       28, 18, 66])

In [101]:
diziOperasyon1>24

array([False,  True, False, False,  True,  True, False, False, False,
        True,  True,  True, False, False, False,  True,  True,  True,
       False,  True])

In [102]:
sonucBoolean=diziOperasyon1>24
sonucBoolean

array([False,  True, False, False,  True,  True, False, False, False,
        True,  True,  True, False, False, False,  True,  True,  True,
       False,  True])

In [103]:
diziOperasyon1[sonucBoolean]

array([73, 67, 27, 38, 29, 72, 32, 41, 28, 66])

In [106]:
diziOperasyon2=np.arange(2,24)
diziOperasyon2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23])

In [113]:
diziOperasyon2+diziOperasyon2

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38, 40, 42, 44, 46])

In [114]:
diziOperasyon2-diziOperasyon2


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [115]:
diziOperasyon2*diziOperasyon2


array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196,
       225, 256, 289, 324, 361, 400, 441, 484, 529])

In [116]:
diziOperasyon2/diziOperasyon2


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.])

In [123]:
diziOperasyon3=[4,9,16,36,81]

In [124]:
np.sqrt(diziOperasyon3)

array([2., 3., 4., 6., 9.])

In [126]:
np.max(diziOperasyon3)

81

In [127]:
np.min(diziOperasyon3)

4